### ISSUE TITLE
Formatted placeholder.

### ISSUE THREAD

**Issue by yiyoperez** [HSGamer/Topper#109]
This plugin currently doesn't accept formatted values to create the leaderboards.

Creating other display types such as top_name, top_value etc... a formatted one (like value_money, value_time) will help players creating leaderboards from raw placeholders and then formatting it into hours format or money format.

The value could also just be "value_formatted" and use formatters section to choose from time, money or any other formatting.

**Comment by HSGamer** [comment]
Use [Formatter expansion](https://api.extendedclip.com/expansions/formatter/)

**Comment by HSGamer** [comment]
And no, plugins must provide placeholders that give raw values

**Comment by yiyoperez** [comment]
> Use [Formatter expansion](https://api.extendedclip.com/expansions/formatter/)

The point is to do it locally, no placeholderapi extension needed.

> And no, plugins must provide placeholders that give raw values. If the plugin doesn't have one, ask the author to add that.

Seems like you misunderstood the suggestion, Im not asking you to create raw values I want to use them to create a leaderboard and then format it by YOU creating a placeholder to format de previously USED raw placeholder/value to create the top.

**Comment by HSGamer** [comment]
I don't want to waste time maintaining parts that others did perfectly.
So, I answered it in both ways:
- If you want to format the top value to some weird formats like short money, time format, etc., then use Formatter expansion. You already have to install PlaceholderAPI to use this plugin anyways, why not a single expansion that did exactly what you need but not limited only to Topper.
- If you want Topper to support formatted placeholders from other plugins when creating leaderboards, then no. Plugins must provide placeholders that give raw values (only numbers and the decimal separator, no weird format). If one plugin doesn't have one, ask its author to add it.

**Comment by HSGamer** [comment]
Duplicated to #93
