### ISSUE TITLE
Remove Formatters, Top Signs and Top Skulls

### ISSUE THREAD

**Issue by HSGamer** [HSGamer/Topper#110]
`formatters` has been available since the beginning of the project. Its usage includes formatting values in the top placeholders and the top signs.

But recently I notice that `formatters` is not perfect, as some of Placeholder expansions did that properly (check [Formatter expansion](https://api.extendedclip.com/expansions/formatter/)).

So, I'm thinking of removing `formatters`, Top Signs and Top Skulls to focus my time on the main purpose of the project "making high-performance leaderboards from single values".

I'm also thinking of making a free plugin that setting Signs and Skulls values based on specific placeholders, so that you can display various things in Signs and Skulls, not just values from Topper.

What is your opinion about this?

**EDIT**: This is for the next big release (3.0.0), so the feature is not suddenly removed. I'm thinking of ways to making it as seamlessly as possible

**Comment by jdkeke142** [comment]
I think it's a good idea to remove the top signs and top skulls from the plugin. 

Most servers are only using placeholders to display leaderboards as holograms or NPCs. Using skulls or signs to display leaderboards seems to me to be an old-fashioned practice.

**Comment by HSGamer** [comment]
Signs & Skulls are now moved to a new plugin called VarBlocks
https://www.spigotmc.org/resources/varblocks.120327/
