### ISSUE TITLE
Folia error 

### ISSUE THREAD

**Issue by iLemon** [HSGamer/Topper#115]
https://pastes.dev/VxxzBbalZq

Have tested both latest on modrinth (2.10.0) and latest from github (8655375) - both result in the same error.

Unsure if helpful but I recommend this if needed: https://github.com/NahuLD/folia-scheduler-wrapper

**Comment by HSGamer** [comment]
That's the error with your LGVoting-Paper plugin, not Topper's error.

We already use our own scheduler wrapper.
