### ISSUE TITLE
add a formatted fucntion for money np 24k not 24000 and add work statistic_played_time placeholder

### ISSUE THREAD

**Issue by alfoons** [HSGamer/Topper#93]
add a formatted fucntion for money np 24k not 24000 and add work statistic_played_time placeholder

**Comment by ArefyNetwork** [comment]
+1, I'd love to see that to format vault money (as I'm using op economy and I've billions, trillions, etc)

**Comment by HSGamer** [comment]
Use the Formatter expansion
https://wiki.placeholderapi.com/users/placeholder-list/#formatter
